.PHONY: clean All

All:
	@echo "----------Building project:[ LongUI - Debug ]----------"
	@"$(MAKE)" -f  "LongUI.mk"
clean:
	@echo "----------Cleaning project:[ LongUI - Debug ]----------"
	@"$(MAKE)" -f  "LongUI.mk" clean
